---
# tasks file for ipam_driver_scaleway
- name: Install IPAM driver dependencies
  ansible.builtin.package:
    name: python3-requests
    state: present

- name: Deploy IPAM driver script
  ansible.builtin.copy:
    src: "{{ ipam_driver_scaleway_src }}"
    dest: "{{ ipam_driver_scaleway_dest }}"
    owner: oneadmin
    group: oneadmin
    mode: '0750'

- name: Configure oned.conf for IPAM driver
  ansible.builtin.lineinfile:
    path: /etc/one/oned.conf
    line: 'IPAM_MAD = [ NAME="scaleway", EXECUTABLE="ipam_scaleway.py" ]'
    regexp: '^IPAM_MAD.*scaleway.*$'
    state: present
  notify: restart opennebula
