on:
  workflow_dispatch:
    inputs:
      customer_name:
        required: true
        type: string
        default: 'opennebula'
      project_name:
        required: true
        type: string
        default: 'scw'
      SCW_DEFAULT_REGION:
        required: true
        type: choice
        default: 'fr-par'
        options:
        - fr-par
        - nl-ams
        - pl-waw
      SCW_DEFAULT_ZONE_NUMBER:
        required: true
        type: choice
        options:
        - 1
        - 2
        - 3
        default: '1'
      scw_infrastructure_project_name:
        required: true
        type: string
        default: 'infra'
      environment:
        required: true
        type: string

jobs:
  init-test-project-exists:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    container:
      image: scaleway/cli:latest
    env: 
      TF_VAR_customer_name:  ${{ inputs.customer_name }}
      TF_VAR_project_name: ${{ inputs.project_name }}
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_ORGANIZATION_ID:  ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      SCW_DEFAULT_REGION: ${{ inputs.SCW_DEFAULT_REGION }}
      SCW_DEFAULT_ZONE:  ${{ inputs.SCW_DEFAULT_REGION }}-${{ inputs.SCW_DEFAULT_ZONE_NUMBER }}
      TF_VAR_scw_infrastructure_project_name: '{ scw_infrastructure_project_name = "${{ inputs.scw_infrastructure_project_name }}"}'
      project_full_name: "${{ inputs.customer_name }}-${{ inputs.project_name }}-${{ inputs.scw_infrastructure_project_name }}"
    steps:
      - name: Assert projects exists
        run:  |
           /scw account project get $project_full_name
